import { describe, expect, it } from "vitest";
import { providerProfilesFixture } from "../test/fixtures";
import { emptyCapabilities } from "./useProviderProfiles";

describe("the capability type mirrors the server's dictionary", () => {
  // types.ts writes out the capability set a second time, by hand, and nothing
  // held it to the first one. The two other mirrors are guarded — a capability
  // the server serves with no copy fails the locale test, and one no group draws
  // fails the deployment form's — but this one could silently fall behind: the
  // field would simply be absent from the type, so every typed path would ignore
  // a capability the server sends and TypeScript would report nothing.
  //
  // emptyCapabilities is the subject rather than the interface because a type has
  // no runtime shape. It is a complete literal of that type, so TypeScript
  // already refuses it if the interface gains a field it does not set or sets one
  // the interface does not have; comparing its keys therefore compares the
  // interface. The server's answer is the endpoint's real one, generated by
  // TestProviderProfilesGoldenMatchesConsoleFixture.
  it("declares exactly the capabilities the server serves, plus the two limits", () => {
    // The limits are part of the type and deliberately not part of the
    // dictionary: they are bounds a deployment declares, not a checkbox.
    const served = [...providerProfilesFixture.capability_names, "max_context_tokens", "max_output_tokens"];
    const declared = Object.keys(emptyCapabilities);

    const missing = served.filter((name) => !declared.includes(name));
    expect(missing, "capabilities the server serves that the type does not declare").toEqual([]);

    const unknown = declared.filter((name) => !served.includes(name));
    expect(unknown, "capabilities the type declares that the server does not serve").toEqual([]);
  });
});
